url: https://maxeskell.github.io/
baseurl: ""

# Site settings
title: Max's portfolio
email: maxeskell@gmail.com
description: "This website showcases my developer skills and experience."


# Team names, titles and social links
people:
- name: Max Eskell
  pic: 1
  position: Leader
  social:
    - title: twitter
      url: #max_eskell
    - title: stack-overflow
      url: #MaxES
    - title: github
      url: #maxeskell

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/max_eskell
  - title: stack-overflow
    url: https://stackoverflow.com/users/7963065/maxes
  - title: github
    url: http://github.com/maxeskell
  - title: linkedin
    url: https://uk.linkedin.com/in/maxeskell

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
