url: https://maxeskell.github.io/
baseurl: ""

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Max Eskell
  pic: 1
  position: Leader
  social:
    - title: twitter
      url: #max_eskell
    - title: stack-overflow
      url: #MaxES
    - title: github
      url: #maxeskell

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/max_eskell
  - title: stack-overflow
    url: http://stackoverflow.com/MaxES
  - title: github
    url: http://github.com/maxeskell

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
